name: CI Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password123
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install all dependencies (workspace)
      run: npm ci

    - name: Run server tests
      run: npm run test:server
      env:
        MONGODB_URI: mongodb://admin:password123@localhost:27017/test?authSource=admin

    - name: Run client tests
      run: npm run test:client
      env:
        CI: true

  lint:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install all dependencies (workspace)
      run: npm ci

    - name: Lint server
      run: npm run lint:server

    - name: Lint client
      run: npm run lint:client

  build-docker:
    runs-on: ubuntu-latest
    needs: [test, lint]
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build server Docker image
      run: |
        cd server
        docker build -t agileflow-server .
        echo "Server Docker image built successfully"

    - name: Build client Docker image
      run: |
        cd client  
        docker build -t agileflow-client .
        echo "Client Docker image built successfully"

    - name: Show built images
      run: |
        docker images
        echo "Docker build completed - Images ready for deployment"